### PR TITLE
[ BB2-805 ] BFD Insights - Implement global-state firehose delivery

### PR DESCRIPTION
**Pull request by dtisza1**
**JIRA Ticket:**
[BB2-805](https://jira.cms.gov/browse/BB2-805)

**User Story or Bug Summary:**

For one BB2 log event, make an inital transport for a BB2 log events out to a Kinesis Firehose delivery stream in preparation for integration in to BFD-insights.

Summary:

This adds deployment repo support for the web server PR:  https://github.com/CMSgov/bluebutton-web-server/pull/959

### What Does This PR Do?

**The following is a list of changes from the commits (including additional comments):**

* Add the ENV variable: `DJANGO_LOG_FIREHOSE_ENABLE = true` to the Jenkinsfiles/Jenkinsfile.cbc-run-django-command and passed in via the ansible command line.

* Add the `DJANGO_LOG_FIREHOSE_CROSSOVER_ROLE_ARN` ENV to the vault settings for test, impl, and prod.

### What Should Reviewers Watch For?

If you're reviewing this PR, please check these things, in particular:

* Are there any unhandled and/or untested edge cases you can think of?
* Does this make any backwards-incompatible changes that might break end user clients?
* Can you find any bugs if you run the code locally and test it manually?
* Naming in general? Do the namings of variables, methods, classes, and other items make sense? Are they too verbose, or not verbose enough? Any redundancies? Are the comments descriptive enough?
* Are audit logging items properly handled? Is sensitive information either not included or hashed?

### What Security Implications Does This PR Have?

Submitters should complete the following questionnaire:

* If the answer to any of the questions below is **Yes**, then here's a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence: N/A.
    * Does this PR add any new software dependencies?  **No**.
    * Does this PR modify or invalidate any of our security controls? **No**.
    * Does this PR store or transmit data that was not stored or transmitted before? **No**.
* If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, and note that this PR should not be merged unless/until he also approves it.
    * Do you think this PR requires additional review of its security implications for other reasons? **No**.

### What Needs to Be Merged and Deployed Before this PR?

NOTE: This needs merged in to master in the deployment repo prior to releasing the BB2-805 PR in the web server repo.

### Submitter Checklist

I have gone through and verified that...:

* [ X] This PR is reasonably limited in scope, to help ensure that:
    1. It doesn't unnecessarily tie a bunch of disparate features, fixes, refactorings, etc. together.
    2. There isn't too much of a burden on reviewers.
    3. Any problems it causes have a small "blast radius".
    4. It'll be easier to rollback if that becomes necessary.
* [ X] I have named this PR and its branch such that they'll be automatically be linked to the (most) relevant Jira issue, per: <https://confluence.atlassian.com/adminjiracloud/integrating-with-development-tools-776636216.html>.
* [X ] This PR includes any required documentation changes, including `README` updates and changelog / release notes entries.
* [X ] All new and modified code is appropriately commented, such that the what and why of its design would be reasonably clear to engineers, preferably ones unfamiliar with the project.
* [X ] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments, which include a JIRA ticket ID for any items that require urgent attention.
* [X ] Reviews are requested from both:
    * At least two other engineers on this project, at least one of whom is a senior engineer or owns the relevant component(s) here.
    * Any relevant engineers on other projects (e.g. BFD, SLS, etc.).
* [X ] Any deviations from the other policies in the [DASG Engineering Standards](https://github.com/CMSgov/cms-oeda-dasg/blob/master/policies/engineering_standards.md) are specifically called out in this PR, above.
    * Please review the standards every few months to ensure you're familiar with them.

### CODE REVIEW

**Comment by dtisza1** [comment]
I was able to successfully test this PR branch using a canary in our TEST environment.

To test, I changed the configuration for the "RUN - Django Command" Jenkins CBC project/job.  This was via the "configuration" settings under the "Pipeline" section by changing the branch specifier from "master" to this PR's branch.  I then used the "Build with parameters" to specify the django command name and canary IP address.

I switched the settings back to use "master" after testing.

**Review by oragame — APPROVED** [review]
LGTM!

**Review by JFU-GIT — APPROVED** [review]
looks good

**Comment by dtisza1** [comment]
NOTE: Closing out this PR. As part of BB2-897 we are going to funnel metrics using an alternate method via Cloudwatch, instead of a Firehose as part of the nightly Jenkins job. So the relate vault setting are no longer needed here.

**Pull request closed without merging**
