### PR TITLE
BB2-782 Add migration parameter to jenkins deploy job

### PR DESCRIPTION
**Pull request by oragame**
**JIRA Ticket:**
[BB2-782](https://jira.cms.gov/browse/BB2-782)

**User Story or Bug Summary:**
As a developer, I need Jenkins prompts reminding me to check for migrations that need to run before or after my work so that the right migrations are run for my deployment.

### What Does This PR Do?
Require the deployment operator to select an option for database migrations related to the deployment. The modified Jenkins job is **DEPLOY - App AMI**. Three options are provided, and a selection is required for the deployment to run. The question and options are:

Are there any migrations required for this deploy?
* [BLANK - triggers an error and aborts the job]
* Pre-Deploy
* Post-Deploy
* No Migrations

### What Should Reviewers Watch For?
* Do the question and answers make good sense?
* Are there any syntax errors, this being a Jenkins job it can not be tested until in master
* Should a cloned Jenkins job be created and tested prior to merging?

If you're reviewing this PR, please check these things, in particular:

* TODO

### What Security Implications Does This PR Have?

Submitters should complete the following questionnaire:

* If the answer to any of the questions below is **Yes**, then here's a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence: N/A.
    * Does this PR add any new software dependencies?  **No**
    * Does this PR modify or invalidate any of our security controls? **No**
    * Does this PR store or transmit data that was not stored or transmitted before? **No**
* If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, and note that this PR should not be merged unless/until he also approves it.
    * Do you think this PR requires additional review of its security implications for other reasons? **No**

### What Needs to Be Merged and Deployed Before this PR?

N/A

### Submitter Checklist

I have gone through and verified that...:

* [X] This PR is reasonably limited in scope, to help ensure that:
    1. It doesn't unnecessarily tie a bunch of disparate features, fixes, refactorings, etc. together.
    2. There isn't too much of a burden on reviewers.
    3. Any problems it causes have a small "blast radius".
    4. It'll be easier to rollback if that becomes necessary.
* [X] I have named this PR and its branch such that they'll be automatically be linked to the (most) relevant Jira issue, per: <https://confluence.atlassian.com/adminjiracloud/integrating-with-development-tools-776636216.html>.
* [X] This PR includes any required documentation changes, including `README` updates and changelog / release notes entries.
* [X] All new and modified code is appropriately commented, such that the what and why of its design would be reasonably clear to engineers, preferably ones unfamiliar with the project.
* [X] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments, which include a JIRA ticket ID for any items that require urgent attention.
* [X] Reviews are requested from both:
    * At least two other engineers on this project, at least one of whom is a senior engineer or owns the relevant component(s) here.
    * Any relevant engineers on other projects (e.g. BFD, SLS, etc.).
* [X] Any deviations from the other policies in the [DASG Engineering Standards](https://github.com/CMSgov/cms-oeda-dasg/blob/master/policies/engineering_standards.md) are specifically called out in this PR, above.
    * Please review the standards every few months to ensure you're familiar with them.

### CODE REVIEW

**Comment by njdister** [comment]
So the idea here is to have the developer make a conscious choice regarding migrations and not allow any sort of default?  I think that makes sense.  The question is, in addition to what you have, should we also add prompts to wait for migrations depending on whether they are pre or post deploy (in this case, before or after terraform applies)?

**Comment by njdister** [comment]
Also yes, its worth either cloning the deploy job for testing, or temporarily changing the existing deploy job to use your branch at least once for a test before merging.

**Comment by oragame** [comment]
> So the idea here is to have the developer make a conscious choice regarding migrations and not allow any sort of default? I think that makes sense. The question is, in addition to what you have, should we also add prompts to wait for migrations depending on whether they are pre or post deploy (in this case, before or after terraform applies)?

Thanks for the review, @njdister . Good question, I asked @nbragdon what the preference is here, and I gather that the main goal is to remind the user to think about migrations when deploying. I like your suggestion though, just in case someone runs the job after answering, the prompts on the console level would be an additional reminder of when to run the migration. Does this sound good to you, Nick?

**Comment by oragame** [comment]
> Also yes, its worth either cloning the deploy job for testing, or temporarily changing the existing deploy job to use your branch at least once for a test before merging.

I am going to go ahead and do this, we can test on the TEST environment if the additional console prompts are added.

**Comment by oragame** [comment]
> > So the idea here is to have the developer make a conscious choice regarding migrations and not allow any sort of default? I think that makes sense. The question is, in addition to what you have, should we also add prompts to wait for migrations depending on whether they are pre or post deploy (in this case, before or after terraform applies)?
> 
> Thanks for the review, @njdister . Good question, I asked @nbragdon what the preference is here, and I gather that the main goal is to remind the user to think about migrations when deploying. I like your suggestion though, just in case someone runs the job after answering, the prompts on the console level would be an additional reminder of when to run the migration. Does this sound good to you, Nick?

After reviewing this a bit further, I think we should move forward as-is without adding the additional prompts in the console. Reason being - When running a job, the migration option is required for the job to even run, so if the answer is "pre-deploy" it's really time to stop there and run the migration. On the other hand if the answer is post-deploy, same thing, we would want to be on standby for to run the migration (before any smoke tests etc...) as soon as the job finishes. If anyone sees potential for problems with this approach lmk.

**Comment by oragame** [comment]
> > Also yes, its worth either cloning the deploy job for testing, or temporarily changing the existing deploy job to use your branch at least once for a test before merging.
> 
> I am going to go ahead and do this, we can test on the TEST environment if the additional console prompts are added.

This testing is complete now with a cloned Jenkins Job (Z DEPLOY - App AMI) - more detailed comments on the Jira ticket.

**Review by njdister — APPROVED** [review]
🌮

**Review by JFU-GIT — COMMENTED** [review]
Tried: build the AMI with BB2-782-Jenkins-prompts-for-db-migrations, then went on to deploy AMI, but somehow it did not prompt with MIGRATION check, but went on to Deploy confirm:

**Review by JFU-GIT — APPROVED** [review]
checked out the "Z Deploy" on Jenkins, looks good.

**Review by dtisza1 — APPROVED** [review]
This looks good to me!  I like this method!

**Pull request merged**
