### PR TITLE
[ BB2-1124 ] Migrate secrets from vault to param store

### PR DESCRIPTION
**Pull request by oragame**
**JIRA Ticket:**
[BB2-1124](https://jira.cms.gov/browse/BB2-1124)

**User Story or Bug Summary:**

As an engineer, we want to migrate ansible-vault config variables used for provisioning instances on AWS from vault to parameter store to eliminate reliance on keybase for sensitive information.

**Scope**
a. Secrets migrated to Parameter store from Vault to remove dependency on Keybase
b. Secrets moved from encrypted vault files for each environment to parameter store, and update the env.yml files to allow pulling values from AWS Parameter Store instead of ansible-vault
**Testing / Documentation**
a. Test via deploy to TEST env first, and then upper env's. When TEST is deployed, we will test the application with standard smoke testing to confirm SLSx as well as connectivity to the database. Django admin is tested for expected functionality.
b. Update README.md and any other documentation which references the vault storage to reflect the move to parameter store for the secrets.

Team reviews handled with the test method outlined in step 2, when the deployment is launched, the AppDev team is notified to perform tests.

### What Does This PR Do?

This PR removes reliance on ansible-vault for secrets management, and migrates the secrets to AWS Parameter Store and AWS Secrets Manager. Also the deployment configuration is modified to handle the update by installing dependencies on base images.

* The main var file affected is the /vars/env/`<env>`/env.yml as the vault secrets were reduced to the "env_" level here. Instead of using the decrypted vault files, we use the ansible lookup plugin to interact with AWS parameter store and pull in the values.
* Modify CBC build image - add boto3 and botocore so aws_ssm lookups could be performed from the build container while provisioning the AMI
* Vault references throughout the repo have been removed in Jenkinsfiles, ansible, documentation etc.
* Changes to the installer used for ansible on the platinum playbook to pip3 instead of yum. Also boto3 and botocore are installed using pip3 to allow the aws_ssm calls to work since the dependency requires ansible >= 3.6 (yum install will install v2)
* TLS certificates are stored on AWS Secrets Manager as they can not be stored in Parameter store. These certs are all pulled using the boot script for each env using the ASG module, and canary env's using aws cli commands. FHIR certs are also stored in AWS Secrets Manager.

### What Should Reviewers Watch For?

If you're reviewing this PR, please check these things, in particular:

* Do the smoke tests and django admin tool work as expected on the canary instances for IMPL and PROD, or in the TEST environment at test.bluebutton.cms.gov?
* Are the README files easy to understand with the updates?
* Do you see any concerns with the build image updates?
* Are there any roles or tasks ion the playbooks that look unnecessary?

### What Security Implications Does This PR Have?

Submitters should complete the following questionnaire:

* If the answer to any of the questions below is **Yes**, then here's a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence: N/A.
    * Does this PR add any new software dependencies? **Yes**.
    * Does this PR modify or invalidate any of our security controls? **Yes**.
    * Does this PR store or transmit data that was not stored or transmitted before? **No**.
* If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, and note that this PR should not be merged unless/until he also approves it.
    * Do you think this PR requires additional review of its security implications for other reasons? **No**.

### What Needs to Be Merged and Deployed Before this PR?

This PR cannot be either merged or deployed until the following pre-requisite changes have been fully deployed:

* CMSgov/some_repo#42

### Submitter Checklist

I have gone through and verified that...:

* [X] This PR is reasonably limited in scope, to help ensure that:
    1. It doesn't unnecessarily tie a bunch of disparate features, fixes, refactorings, etc. together.
    2. There isn't too much of a burden on reviewers.
    3. Any problems it causes have a small "blast radius".
    4. It'll be easier to rollback if that becomes necessary.
* [X] I have named this PR and its branch such that they'll be automatically be linked to the (most) relevant Jira issue, per: <https://confluence.atlassian.com/adminjiracloud/integrating-with-development-tools-776636216.html>.
* [X] This PR includes any required documentation changes, including `README` updates and changelog / release notes entries.
* [X] All new and modified code is appropriately commented, such that the what and why of its design would be reasonably clear to engineers, preferably ones unfamiliar with the project.
* [x] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments, which include a JIRA ticket ID for any items that require urgent attention.
* [X] Reviews are requested from both:
    * At least two other engineers on this project, at least one of whom is a senior engineer or owns the relevant component(s) here.
    * Any relevant engineers on other projects (e.g. BFD, SLS, etc.).
* [x] Any deviations from the other policies in the [DASG Engineering Standards](https://github.com/CMSgov/cms-oeda-dasg/blob/master/policies/engineering_standards.md) are specifically called out in this PR, above.
    * Please review the standards every few months to ensure you're familiar with them.

### CODE REVIEW

**Review by JFU-GIT — APPROVED** [review]
Good work, thanks!

**Review by dtisza1 — CHANGES_REQUESTED** [review]
@oragame Just had that one change we chatted about in Slack. 

I logged in to the canaries to check with the running instances to do side-by-side comparisons. This looked good to me!

**Comment by oragame** [comment]
> @oragame Just had that one change we chatted about in Slack.
> 
> I logged in to the canaries to check with the running instances to do side-by-side comparisons. This looked good to me!

@dtisza1 I updated the permissions on the cert/key files to 0640. Deployed all new canaries and deployed also to TEST to verify, and smoke tests looked good. Thanks for the good catch here, Dave!

**Review by dtisza1 — APPROVED** [review]
This looks good to me!

@oragame Great work on this!!!

**Review by StewGoin — APPROVED** [review]
This looks good to me -- I did notice some region specific items related to SSM ("region='us-east-1'") -- if that's a regional limitation it's not a show stopper but something we should make note of for any implications for disaster recovery or future multi-region desires.

**Comment by oragame** [comment]
> This looks good to me -- I did notice some region specific items related to SSM ("region='us-east-1'") -- if that's a regional limitation it's not a show stopper but something we should make note of for any implications for disaster recovery or future multi-region desires.

Thanks for the review, Jason. Good call out on the region setting. Sounds like a good place to script a pull and push from one region to another.

**Pull request merged**
