### PR TITLE
[ BB2-56 ] SecCom: Assign individual app server ssh keys

### PR DESCRIPTION
**Pull request by oragame**
**JIRA Ticket:**
[BB2-56](https://jira.cms.gov/browse/BB2-56)

**User Story or Bug Summary:**

As a BB Engineer, I want to implement using individual keys for accessing the BB2 application servers via SSH so that the systems comply with CMS security requirements and to keep our systems secure.

### What Does This PR Do?
PROVISION SSH PUBLIC KEYS TO PLAT. AMI
* Add an ansible role that will provision SSH Keys 
* Have the role run during the platinum image build 
* Add `shared/vault.yml` for user info

**Below testing steps passed:**
* Build platinum AMI with this branch
* Build app AMI using the platinum and this branch
* Deploy a test canary
* Test user access and sudo

### What Should Reviewers Watch For?
Once all public keys are provided, I will deploy a test canary and provide the IP here - everyone should test their ssh access and confirm it works.

If you're reviewing this PR, please check these things, in particular:

* Maybe check the vault file formatting
* I made one change to the role compared to the BFD version, added `when: item.sudoer == "true"` in the `Add user to sudoers file` task - this was to allow a condition that would not skip this task in the Jenkins build.

### What Security Implications Does This PR Have?

Submitters should complete the following questionnaire:

* If the answer to any of the questions below is **Yes**, then here's a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence: N/A.
    * Does this PR add any new software dependencies? **No**.
    * Does this PR modify or invalidate any of our security controls? **No**.
    * Does this PR store or transmit data that was not stored or transmitted before? **No**.
* If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, and note that this PR should not be merged unless/until he also approves it.
    * Do you think this PR requires additional review of its security implications for other reasons? **No**.

### What Needs to Be Merged and Deployed Before this PR?

N/A

### Submitter Checklist

I have gone through and verified that...:

* [X] This PR is reasonably limited in scope, to help ensure that:
    1. It doesn't unnecessarily tie a bunch of disparate features, fixes, refactorings, etc. together.
    2. There isn't too much of a burden on reviewers.
    3. Any problems it causes have a small "blast radius".
    4. It'll be easier to rollback if that becomes necessary.
* [X] I have named this PR and its branch such that they'll be automatically be linked to the (most) relevant Jira issue, per: <https://confluence.atlassian.com/adminjiracloud/integrating-with-development-tools-776636216.html>.
* [ ] This PR includes any required documentation changes, including `README` updates and changelog / release notes entries.
* [x] All new and modified code is appropriately commented, such that the what and why of its design would be reasonably clear to engineers, preferably ones unfamiliar with the project.
* [X] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments, which include a JIRA ticket ID for any items that require urgent attention.
* [x] Reviews are requested from both:
    * At least two other engineers on this project, at least one of whom is a senior engineer or owns the relevant component(s) here.
    * Any relevant engineers on other projects (e.g. BFD, SLS, etc.).
* [X] Any deviations from the other policies in the [DASG Engineering Standards](https://github.com/CMSgov/cms-oeda-dasg/blob/master/policies/engineering_standards.md) are specifically called out in this PR, above.
    * Please review the standards every few months to ensure you're familiar with them.

### CODE REVIEW

**Comment by oragame** [comment]
Still waiting on a few public keys, but the commits can be reviewed.

**Review by njdister — CHANGES_REQUESTED** [review]
Great work! The only change I would make is to remove the password field from each entry in the vault entirely. We want to make sure the password is unset, and not set to an empty string (not sure if this is technically possible but just to be safe). This is how the entries are set in the BFD vault.

**Comment by njdister** [comment]
Redacted snapshot from the BFD vault:
```
ssh_users:
  - username: nathan.dister
    sudoer: true
    public_key: "ssh-rsa XXX
  - username: john.zulim
    sudoer: true
    public_key: "ssh-rsa XXX
```

**Comment by oragame** [comment]
> Great work! The only change I would make is to remove the password field from each entry in the vault entirely. We want to make sure the password is unset, and not set to an empty string (not sure if this is technically possible but just to be safe). This is how the entries are set in the BFD vault.

FWIW - I tested the blank password which is not allowed for access, but removing the password field is much cleaner/less confusing and leaves no room for question. Just removed and testing the build now. Thanks!

**Review by njdister — APPROVED** [review]
Just re-reviewed, LGTM!

**Pull request merged**
