### PR TITLE
Fix Platinum AMI Build

### PR DESCRIPTION
**Pull request by loganbertram**
**JIRA Ticket:**
[BB2-3175](https://jira.cms.gov/browse/BB2-3175)

**User Story or Bug Summary:**

As a BB2.0 User, I want the BB2.0 Team to have a reliable and usable Platinum AMI deployment Pipeline
So that the deployments and infrastructure are more stable allowing for the development of enhanced features and security updates

### What Does This PR Do?
This PR reverts changes made during our Gold -> Platinum AMI build incident, restoring the yum minimal security updates and removing the unnecessary adjustments made and partially commented out in various commits trying to resolve the incident.

### What Should Reviewers Watch For?

This is fairly simple. Most of what changed is removing comments. Otherwise, we're reintroducing the failing yum security update. As long as Gold images are being built using this branch, this is working as before.

One such run has been completed and can be found [here](https://ci.backends.cms.gov/non-oc/job/Blue%20Button/job/BUILD%20-%20Platinum%20AMI%20(AMZN%202)/299/)

### What Security Implications Does This PR Have?

Submitters should complete the following questionnaire:

* If the answer to any of the questions below is **Yes**, then here's a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence: N/A.
    * Does this PR add any new software dependencies? *No**.
    * Does this PR modify or invalidate any of our security controls? **No**.
    * Does this PR store or transmit data that was not stored or transmitted before? **No**.
* If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, and note that this PR should not be merged unless/until he also approves it.
    * Do you think this PR requires additional review of its security implications for other reasons? **No**.

### Submitter Checklist

I have gone through and verified that...:

* [x] This PR is reasonably limited in scope, to help ensure that:
    1. It doesn't unnecessarily tie a bunch of disparate features, fixes, refactorings, etc. together.
    2. There isn't too much of a burden on reviewers.
    3. Any problems it causes have a small "blast radius".
    4. It'll be easier to rollback if that becomes necessary.
* [x] I have named this PR and its branch such that they'll be automatically be linked to the (most) relevant Jira issue, per: <https://confluence.atlassian.com/adminjiracloud/integrating-with-development-tools-776636216.html>.
* [x] This PR includes any required documentation changes, including `README` updates and changelog / release notes entries.
* [x] All new and modified code is appropriately commented, such that the what and why of its design would be reasonably clear to engineers, preferably ones unfamiliar with the project.
* [x] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments, which include a JIRA ticket ID for any items that require urgent attention.
* [x] Reviews are requested from both:
    * At least two other engineers on this project, at least one of whom is a senior engineer or owns the relevant component(s) here.
    * Any relevant engineers on other projects (e.g. BFD, SLS, etc.).
* [x] Any deviations from the other policies in the [DASG Engineering Standards](https://github.com/CMSgov/cms-oeda-dasg/blob/master/policies/engineering_standards.md) are specifically called out in this PR, above.
    * Please review the standards every few months to ensure you're familiar with them.

### CODE REVIEW

**Comment by jimmyfagan** [comment]
Logan, to clarify, did you test a platinum build run with this branch in Jenkins? If so, can you maybe point to that run in the description?

**Comment by loganbertram** [comment]
@jimmyfagan Yep! This last run was completed with these changes, using the branch selection config added in Jenkins: 

https://ci.backends.cms.gov/non-oc/job/Blue%20Button/job/BUILD%20-%20Platinum%20AMI%20(AMZN%202)/297/

**Comment by jimmyfagan** [comment]
Ah okay, looking at the output there, it seems like it was actually run on master. I had updated the DEPLOY_REPO_BRANCH param description to say
```
The branch of the deployment repo to build in AMI. Defaults to master. (Note: this is currently an aspirational parameter, it doesn't actually work. To run on a branch, you can go into https://ci.backends.cms.gov/non-oc/job/Blue%20Button/job/BUILD%20-%20Platinum%20AMI%20(AMZN%202)/configure and change the branch specifier to point directly to your branch. Be sure to set it back to `master` when you're done.)
```
but it must have gotten reset, maybe automatically based on the Jenkinsfile. But anyway, in the output I don't see the "Apply security patches" task in the logs. If you go to the configure page and change the branch and run again, we'll see what happens, but I'm worried that it won't be this simple if there's still some incompatibility with the gold image. 🤞

**Comment by loganbertram** [comment]
Strange. Here's the parameters from that run:
Screenshot 2024-05-07 at 10 14 04 AM
It looks like that option isn't being picked up...

I just re-ran and it's still grabbing master instead of the branch set in parameters.

**Comment by loganbertram** [comment]
Ok! We have a success here: https://ci.backends.cms.gov/non-oc/job/Blue%20Button/job/BUILD%20-%20Platinum%20AMI%20(AMZN%202)/299/ so this should really be good to go.

**Review by jimmyfagan — APPROVED** [review]
I see the successful build, glad it worked out! Approved!

**Pull request merged**
