### PR TITLE
jimfuqian/BB2-2980 Update python to 3.11 per python upgrade on bb2 server

### PR DESCRIPTION
**Pull request by JFU-NAVA-PBC**
**JIRA Ticket:**
[BB2-2980](https://jira.cms.gov/browse/BB2-2980)

**User Story or Bug Summary:**

Support for the current version of Python (3.8) will end in October 2024.  It will need to be updated before that time. This spike is to review the size of the upgrade to the latest version of Python. 

Considerations:

How big of an upgrade is it (small, medium, or large)?
Any major sections of code affected or broken?
Estimated effort to complete the upgrade.
What version should we target (early conversations suggest 3.11/3.12)?
Python 3.9 LTS ends Oct 2025, my 2c is that upgrade python stack following the LTS/EOL pipeline, instead of jump to higher versions unless there is a feature in that higher version that BB2 really need.

### What Does This PR Do?

Deployment artifacts updates to match the bb2 server side python upgrade to 3.11

### What Should Reviewers Watch For?

If you're reviewing this PR, please check these things, in particular:

* TODO

### What Security Implications Does This PR Have?

Submitters should complete the following questionnaire:

* If the answer to any of the questions below is **Yes**, then here's a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence: N/A.
    * Does this PR add any new software dependencies? **Yes** or **No**.
    * Does this PR modify or invalidate any of our security controls? **Yes** or **No**.
    * Does this PR store or transmit data that was not stored or transmitted before? **Yes** or **No**.
* If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, and note that this PR should not be merged unless/until he also approves it.
    * Do you think this PR requires additional review of its security implications for other reasons? **Yes** or **No**.

### What Needs to Be Merged and Deployed Before this PR?

This PR cannot be either merged or deployed until the following pre-requisite changes have been fully deployed:

* CMSgov/some_repo#42

### Submitter Checklist

I have gone through and verified that...:

* [x] This PR is reasonably limited in scope, to help ensure that:
    1. It doesn't unnecessarily tie a bunch of disparate features, fixes, refactorings, etc. together.
    2. There isn't too much of a burden on reviewers.
    3. Any problems it causes have a small "blast radius".
    4. It'll be easier to rollback if that becomes necessary.
* [x] I have named this PR and its branch such that they'll be automatically be linked to the (most) relevant Jira issue, per: <https://confluence.atlassian.com/adminjiracloud/integrating-with-development-tools-776636216.html>.
* [ ] This PR includes any required documentation changes, including `README` updates and changelog / release notes entries.
* [x] All new and modified code is appropriately commented, such that the what and why of its design would be reasonably clear to engineers, preferably ones unfamiliar with the project.
* [x] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments, which include a JIRA ticket ID for any items that require urgent attention.
* [x] Reviews are requested from both:
    * At least two other engineers on this project, at least one of whom is a senior engineer or owns the relevant component(s) here.
    * Any relevant engineers on other projects (e.g. BFD, SLS, etc.).
* [x] Any deviations from the other policies in the [DASG Engineering Standards](https://github.com/CMSgov/cms-oeda-dasg/blob/master/policies/engineering_standards.md) are specifically called out in this PR, above.
    * Please review the standards every few months to ensure you're familiar with them.

### CODE REVIEW

**Comment by StewGoin** [comment]
I think this repo and the bb-static-site need their templates updated to yoink my username out of them just FYI.

**Comment by JFU-NAVA-PBC** [comment]
> I think this repo and the bb-static-site need their templates updated to yoink my username out of them just FYI.

Apology for that, will bring this up tomorrow and get this fixed, have a great rest of the day Jason ;-)

**Comment by StewGoin** [comment]
No worries, there are bound to be repos that got missed on the first pass. We have so many!

**Comment by JFU-NAVA-PBC** [comment]
close this DPR since the python upgrade to 3.11 has been completed

**Pull request closed without merging**
